name: perltidy
on: [push, pull_request]
jobs:
   perltidy:
    runs-on: ubuntu-latest
    container:
      image: perl:5.32
    steps:
       - uses: actions/checkout@v2
       - name: perl -V
         run: perl -V
       - name: Install dependencies
         run: cpanm -n Perl::Tidy Perl::Critic Perl::Critic::Policy::Freenode::DiscouragedModules Perl::Critic::Policy::Freenode::PackageMatchesFilename
       - name: perltidy --version
         run: perltidy --version
       - name: Run perltidy
         shell: sh
         run: make check
